name: chargo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  inner_drawer: ^1.0.0+1
  firebase_core: ^2.13.1
  flutter_stripe: ^9.2.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  sliding_up_panel2: ^3.3.0+1
  snapping_sheet_2: ^3.1.5
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
